### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#17]
Line up contact form with nav bar.
<img width="754" alt="screen shot 2016-06-20 at 10 43 00 am" src="https://cloud.githubusercontent.com/assets/20047847/16200439/fa46175c-36d2-11e6-971b-3f2d47d69285.png">

**Comment by 808loud** [comment]
If the contact form is lined up with the nav bar, it won't be lined up with the main content column. Is this what you want?

**Comment by charlydsgn** [comment]
For now, yes. Also, make sure the lines are the same width as the nav bar. When it breaks to mobile view the lines do not need to line up, but centered with the nav bar.

**Comment by charlydsgn** [comment]
If it's a lot of work you can hold off for now. It looks much better!
