### ISSUE TITLE
Hero image

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#18]
Crop needs to be more in line with the mock up. It should be 424px height. Also, crop needs to stay close to what it is now when scaled, similar to https://dogvacay.com
<img width="760" alt="screen shot 2016-06-20 at 10 51 33 am" src="https://cloud.githubusercontent.com/assets/20047847/16200876/b85b5224-36d4-11e6-9c0b-ffc514f221a9.png">

**Comment by 808loud** [comment]
That presentation is not possible with a fixed background image (parallax effect). I have removed the parallax effect from the hero image.

These changes should give you what you're looking for.
Preview here: http://rawgit.com/808loud/charlie-portfolio/master/public/index.html

Closing this issue now. Please reopen it if this is not what you want.
