### ISSUE TITLE
Charlie type treatment

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#22]
Make the same size/spacing as "Work, Process, Booking"
<img width="222" alt="screen shot 2016-06-21 at 6 35 35 pm" src="https://cloud.githubusercontent.com/assets/20047847/16249802/3d65330e-37de-11e6-8be0-0a7b7487e86c.png">

**Comment by 808loud** [comment]
Fixed with https://github.com/808loud/charlie-portfolio/commit/8a49987300b318527a969363a14c658d8ddb5ce9
