### ISSUE TITLE
Footer button spacing in mobile, and functionality updates

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#28]
Can spacing be fixed so it is consistent? Refer to mockup. 
<img width="386" alt="screen shot 2016-06-21 at 6 52 30 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250121/93c6a82a-37e0-11e6-8f80-4fc2285bea3b.png">
<img width="420" alt="screen shot 2016-06-21 at 6 53 33 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250135/a7260ff0-37e0-11e6-9c27-766dd9dff270.png">

**Comment by 808loud** [comment]
When fixing this, also link Mpls to Google Maps, and make the phone number a tel="" link
