### ISSUE TITLE
Center brand logos in project preview

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#29]
Center all logos between button and top of bar. 
<img width="476" alt="screen shot 2016-06-21 at 6 55 49 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250192/003dd4c4-37e1-11e6-9215-abac1bdf5129.png">

**Comment by 808loud** [comment]
Assigning this to @charlydsgn until I get updated graphics.
