### ISSUE TITLE
Line Spacing

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#32]
Make consistent with similar text. 3rd line looks too spaced. 
<img width="571" alt="screen shot 2016-06-21 at 7 03 02 pm" src="https://cloud.githubusercontent.com/assets/20047847/16250313/09c748e4-37e2-11e6-81ab-6bd37157d4b8.png">

**Comment by 808loud** [comment]
Fixed with https://github.com/808loud/charlie-portfolio/commit/e341165e56ac4f633b7f0afba79a5cfdae6bd189
