### ISSUE TITLE
project preview background image centering in FF

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#49]
In Chrome the images within the bar center, in Firefox it doesn't. 

<img width="567" alt="screen shot 2016-06-23 at 2 18 51 pm" src="https://cloud.githubusercontent.com/assets/20047847/16316544/ad2c0b76-394c-11e6-838e-7bddf693a0ec.png">

**Comment by 808loud** [comment]
Possibly due to the missing browser prefixes on background-size. 

Potential fix is on the develop branch. I'll test tomorrow when I have access to a device with Firefox installed.

**Comment by 808loud** [comment]
This looks fixed on my end (Windows 7 Firefox). 

@charlydsgn can you confirm on your OS X Firefox?
