### ISSUE TITLE
(Mobile Device) Hamburger menu color when toggling from "X" back to hamburger

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#52]
When tapping the hamburger menu, then tapping the X, the hamburger icon does not change back to grey. See below. On my desktop it works fine. 

![img_8093](https://cloud.githubusercontent.com/assets/20047847/16322720/cd4babb4-396a-11e6-821e-c6105ce436ef.PNG)
![img_8094](https://cloud.githubusercontent.com/assets/20047847/16322721/cd54c186-396a-11e6-8d7b-c7e90be183bc.PNG)

**Comment by 808loud** [comment]
A few questions:
1. I assume this is Safari / iOS, correct?
2. Are you testing mobile and desktop both on the master preview site?
3. Are any other icons white in your mobile browser?
4. Is the hamburger menu off-white when the page first loads? And it only shows in the wrong color after toggling the menu open and then closed?

**Comment by charlydsgn** [comment]
1. I assume this is Safari / iOS, correct?
   **Yes**
2. Are you testing mobile and desktop both on the master preview site?
   **Yes, it performs the same in Develop**
3. Are any other icons white in your mobile browser?
   **All text within the buttons, including the largest text is white, should be the off-white color**
4. Is the hamburger menu off-white when the page first loads? And it only shows in the wrong color after toggling the menu open and then closed?
   **Yes**

**Comment by 808loud** [comment]
For 3, I understand the expected result, but what is the actual result that you are seeing?

**Comment by 808loud** [comment]
I don't quite understand your reply to 3. Are you saying that all button text is white on Safari mobile? I understand the expected result is off-white, but I am trying to clarify the actual result.

**Comment by charlydsgn** [comment]
Are you saying that all button text is white on Safari mobile?
**Yes, the only place where the color is off white is the background color**

**Comment by charlydsgn** [comment]
Ignore my comment to 3. When I downloaded the screen grab from my phone to my laptop and enlarged I discovered that the text/icons are the off white color. Sorry for the confusion.

**Comment by 808loud** [comment]
OK. I am closing this issue. If there is a misunderstanding and something is still not working as expected, please reopen this issue and clarify. Thanks.
