### ISSUE TITLE
(Mobile device) container padding

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#53]
Not sure if you're aware. Padding went away in the modals. 
<img width="462" alt="screen shot 2016-06-24 at 1 32 36 pm" src="https://cloud.githubusercontent.com/assets/20047847/16346995/ddd29858-3a0f-11e6-8427-4aed34d4510c.png">

**Comment by 808loud** [comment]
Will fix. Was caused by working on that pesky X button in the modals.

**Comment by 808loud** [comment]
Fixed on dev
