### ISSUE TITLE
hamburger menu

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#54]
Another one of those not sure if you're aware already things. Hamburger icon is now off center. It looks too narrow, please make a little wider so it's centered in the box. 
<img width="480" alt="screen shot 2016-06-24 at 1 39 24 pm" src="https://cloud.githubusercontent.com/assets/20047847/16347082/6d986c24-3a10-11e6-8fa0-434a66ac260d.png">

**Comment by 808loud** [comment]
Yep, I will go back and fix this. It's a result of justifying the nav menu, footer buttons, and form width. 

But thanks for the reminder. I'll leave it open until it's fixed.

**Comment by 808loud** [comment]
Related to #55

**Comment by 808loud** [comment]
Fixored
