### ISSUE TITLE
Position footer buttons and modal arrow_up button 34px from bottom of viewport

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#55]
Padding should probably be consistent for the buttons. Match footer padding (below buttons) to header padding(above buttons). Treat the same for the modal buttons.
<img width="1241" alt="screen shot 2016-06-24 at 3 29 59 pm" src="https://cloud.githubusercontent.com/assets/20047847/16349666/ac8725f6-3a1f-11e6-825d-f4a28ff18fea.png">
<img width="940" alt="screen shot 2016-06-24 at 3 28 23 pm" src="https://cloud.githubusercontent.com/assets/20047847/16349668/ac8a981c-3a1f-11e6-9832-2a93bbce6388.png">
<img width="725" alt="screen shot 2016-06-24 at 3 28 04 pm" src="https://cloud.githubusercontent.com/assets/20047847/16349667/ac89dde6-3a1f-11e6-81d1-657cadc10665.png">

**Comment by 808loud** [comment]
Would love to do that, as it would really simplify my code and make my life easier... however, it would make the header nav bar narrower than the footer nav bar and the contact form.

If you want me to implement, I would be happy to revert the code that stretches them out. However, to reiterate, it will prevent me from justifying the header nav bar, the footer nav bar, and the contact form.

**Comment by charlydsgn** [comment]
Could you just add padding to the arrow in the modal then?

**Comment by 808loud** [comment]
Arrow_up button is currently 50px wide to match up with the "static" X button in the modal. 

It also has the same padding as all buttons (other than the header nav buttons, which have an additional 3px of padding-left and padding-right to justify the nav element).

How would you like me to change the arrow_up button's padding?

**Comment by charlydsgn** [comment]
Ah, I see that there is padding in chrome but not firefox. Why can't browsers get their act together! Lets just put this on the back burner for now unless it's a quick fix.

**Comment by 808loud** [comment]
It ought to be the same, as I am using cross-browser compatible code to add style the buttons.

Is this related to browser zoom, perhaps?

**Comment by charlydsgn** [comment]
In Safari and Firefox the arrow button sits on the edge of the browser window, no padding. Padding only shows up in chrome.

**Comment by charlydsgn** [comment]
This isn't core to the functionality. I'd rather focus on the few things that are left, which I believe is the snapping of the nav bar to the right spot, the image not scaling above the contact form on my mobile device, and just noticed the work links do not work when I tap on my phone. 

Going to lay low for a little bit and check-in on Sunday. Let me know when the site is ready and will give it one last look before going live.

**Comment by 808loud** [comment]
Which work links are you referring to that are not working on your phone? Please open a new issue for that.

And now I see what you're referring to in this issue (#55). I was confused when you said padding... A web dev would call that margin. Or whitespace under the button would be universally understood ;-)

I will look into a fix later.

**Comment by charlydsgn** [comment]
Ha, in print I would call it margin too, and here I thought I was being savvy.
