### ISSUE TITLE
Modals not firing [iPhone 5S]

### ISSUE THREAD

**Issue by 808loud** [808loud/charlie-portfolio#58]
@charlydsgn I am trying to troubleshoot this issue.

Can you tell me if the following JS-based functionality is working on your device?
1. Mobile menu expand/collapse
2. Slideshow
3. Do all the slides display at the same height... or are they different sizes when the quotes are different lengths?

**Comment by 808loud** [comment]
Another important distinction... 

Do the modals work on you device when you visit the master preview site?

http://rawgit.com/808loud/charlie-portfolio/master/public/index.html#work

**Comment by charlydsgn** [comment]
Mobile menu works. Still remains clay color when tapping in/out of
hamburger.
Slideshow does not work at all in mobile

Charlie Tetreault
chrliedsgn@gmail.com
612.481.9481

**Comment by charlydsgn** [comment]
I am viewing master preview in mobile. The modals and slide show work when
I tap this link. Weird, I was using the same link yesterday, closed all
windows, restarted my phone and everything.

Charlie Tetreault
chrliedsgn@gmail.com
612.481.9481

**Comment by 808loud** [comment]
Could have been be a caching issue. A restart usually won't clear a browser's cache - you usually have to do it manually or use a private (aka incognito) window.

Closing this, as it sounds like it is solved.
