### ISSUE TITLE
Overall margins

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#66]
Make sure left/right margins are consistent in mobile view. See below.
<img width="373" alt="screen shot 2016-06-27 at 7 23 20 pm" src="https://cloud.githubusercontent.com/assets/20047847/16399871/d827e802-3c9b-11e6-9180-a22248f9c60a.png">
<img width="360" alt="screen shot 2016-06-27 at 7 23 04 pm" src="https://cloud.githubusercontent.com/assets/20047847/16399872/d82be48e-3c9b-11e6-8be5-5e242222c1e3.png">

**Comment by 808loud** [comment]
@charlydsgn does everything look good on develop?

http://rawgit.com/808loud/charlie-portfolio/develop/public/index.html

**Comment by 808loud** [comment]
Repoening this while I compare my code to what's currently in the live environment.
