### ISSUE TITLE
Site left/right scrolling

### ISSUE THREAD

**Issue by charlydsgn** [808loud/charlie-portfolio#67]
Just making sure you are aware that the site now scrolls left/right whereas before it did not. See below. 
<img width="1334" alt="screen shot 2016-06-27 at 7 25 24 pm" src="https://cloud.githubusercontent.com/assets/20047847/16399901/26efba1e-3c9c-11e6-95ef-225ed65c4912.png">

**Comment by 808loud** [comment]
Caused by #65 - will revert and fix
